### ISSUE TITLE
Dump DYNPRO_SEND_IN_BACKGROUND for certain Artifacts with Namespaces

### ISSUE THREAD

**Issue by thorsten-wolf-neptune** [abapGit/abapgit-api-rfc#7]
Hi me again,

we do experience a dump in st22 when we try to call ZABAPGIT_API_RFC_PULL.
[dump.pdf](https://github.com/abapGit/abapgit-api-rfc/files/11757307/dump.pdf)

Here my finding: When trying to pull a repository that contains SAP artifacts that are having a namespace. 
Then a Dynpro Popup would show  up for certain SAP artifact types:
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/d2aa3110-a5cb-402c-bbe6-ba8d34aca627)

The message in that dynpro is always the same (at least in our case) and is related to the namespace.
As of now i identified:
**ACID** -> Checkpoint Groups (Transaction SAAB)
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/7ea088d8-6a0d-4807-b9b8-fd6d380e3d10)

**ENHS** -> Enhancement Spots (Transaction SE20)
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/81cbe270-81c2-4d43-b322-4cffb38c5e0b)

and **SOTR** Texts (come into play when using exception classes that are not message class based)
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/748feed8-b4fd-42ef-8a33-076425ecabd6)

It comes up because in the deserialize process some internal sap function modules/classes call function module **TRINT_OBJECTS_CHECK_AND_INSERT** with parameter IV_DIALOG <> space

so abapgit cannot really influence it 😞 

I see one "dirty" workaround:
That popup has two buttons: 1 "normal" ok 
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/d6960c11-375a-434b-aa92-e3b4da3151d8)

and 2. "Furhter for all".
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/9cbb8add-b220-4e42-9f50-9bbf5a63e44a)

SAP will check if the message that is about to be shown already accepted with "OK for all" with a global internal table called **gt_confirmed_messages**. If so they don't show that popup:
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/8a0bf8d9-109c-44b8-b23a-b5ad85a548a5)

so in my very dirty workaround i did the following: hack the global internal table with a dirty assign 😄 
At the very beginning of ZABAPGIT_API_RFC_PULL the following code works to bypass the issue:
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/4ffbe60f-555c-42c5-927b-6d8b503c99c4)
```abap
  " BEGIN WORKAROUND FOR POPUP "Object can only be created  in package of namespace ..."
  types: begin of gty_message,
           id type symsgid,
           ty type symsgty,
           no type symsgno,
           v1 type symsgv,
           v2 type symsgv,
           v3 type symsgv,
           v4 type symsgv,
         end of gty_message,
         gtyt_message type standard table of gty_message.

  data: ls_confirmed_message type gty_message.

  field-symbols: <gt_confirmed_messages> type gtyt_message.

  " dummy call to load the function group into memory in order to access the global gt_confirmed_messages itab.
  call function 'TR_READ_CURRENT_ACTIVITY'.

  " try to get the gt_confirmed_messages itab.
  assign ('(SAPLSTRD)GT_CONFIRMED_MESSAGES') to <gt_confirmed_messages>.
  if sy-subrc = 0.
    " got it! now simulate there has been a "Further for all" button press for the necessary messages.
    " that prevents the popup to be shown in (SAPLSTRD)raise_error_or_send_popup
    " as of now we are only aware of the message "Object can only be created  in package of namespace ..."
    ls_confirmed_message-id = 'TR'.
    ls_confirmed_message-no = '007'.
    insert ls_confirmed_message into table <gt_confirmed_messages>.
  endif.
  " END WORKAROUND FOR POPUP "Object can only be created  in package of namespace ..."
```

any ideas what else we could do to cover this problem? Dirty assigns are the worst to do i know 😃 but i am afraid that is the only solution we have for this...

**Comment by thorsten-wolf-neptune** [comment]
here the dump again in case you cannot open the pdf.
![image](https://github.com/abapGit/abapgit-api-rfc/assets/83953375/8533461b-d923-4771-9525-226320918b02)

**Comment by larshp** [comment]
I think this is a generic abapGit issue, not only related to the RFC code, ideally a pull should not show additional gui, also when/if moving to all http gui

**Comment by thorsten-wolf-neptune** [comment]
true. moving to a full non-sap-gui-solution abapgit itself would also face that issue. Should I put this issue in the abapgit repo for a broader audience and dicussion?

**Comment by larshp** [comment]
yes please

**Comment by thorsten-wolf-neptune** [comment]
i cannot transfer this issue. should i just create a new one there? https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by larshp** [comment]
just create a new one
